In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
#import class pandas and it is renamed to pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
# dataset is Assigned to class pandas(pd) dot function name read_csv("csvfile Name.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age','bmi','children','sex_male','smoker_yes']]
#input(YearsExperience) is assigned to variable independent
#closed Double bracket used for calling one column fromthe .csv file

In [8]:
dependent=dataset[["charges"]]
##Output(Salary) is assigned to variable dependent
#closed Double bracket used for calling one column fromthe .csv file

In [9]:
from sklearn.model_selection import train_test_split
#To reduce the memory import perticular small function(train_test_split) from library (sklearn) Class (model_selection)
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)
# X- input(independent), y- Output(dependent). separate the data set 30 percentage to Test set and remaining to Training set

In [10]:
from sklearn.tree import DecisionTreeRegressor

In [11]:
from sklearn.model_selection import GridSearchCV
param_grid ={'criterion':['mse','mae','friedman_mse',],'max_features':['auto','sqrt','log2'],'splitter':['random','best']}
grid = GridSearchCV(DecisionTreeRegressor(),param_grid,refit= True,verbose=3,n_jobs=-1)
#fitting the model for grid search ('squared_error','absolute_error','poisson')
grid.fit(independent,dependent)

C:\Users\skishor.kumar\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.

Fitting 3 folds for each of 18 candidates, totalling 54 fits

[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:    3.5s
[Parallel(n_jobs=-1)]: Done  39 out of  54 | elapsed:    3.7s remaining:    1.4s
[Parallel(n_jobs=-1)]: Done  54 out of  54 | elapsed:    3.7s finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=DecisionTreeRegressor(criterion='mse', max_depth=None,
                                             max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             presort=False, random_state=None,
                                             splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['random', 'best']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [12]:
#print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'mae', 'max_features': 'auto', 'splitter': 'random'}:

In [13]:
table=pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015623,8.778064e-07,0.000000,0.000000,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.687704,0.690015,0.703266,0.693662,0.006857,4
1,0.010416,7.365415e-03,0.000000,0.000000,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.704047,0.652643,0.708731,0.688474,0.025408,8
2,0.005208,7.365246e-03,0.010415,0.007364,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.682538,0.651188,0.587319,0.640348,0.039621,14
3,0.000000,0.000000e+00,0.010418,0.007366,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.720576,0.676792,0.635078,0.677482,0.034908,10
4,0.015620,3.146965e-06,0.000000,0.000000,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.621333,0.616603,0.567591,0.601842,0.024296,17
5,0.010415,7.364797e-03,0.005208,0.007365,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.680852,0.659249,0.685095,0.675065,0.011317,11
6,0.031249,0.000000e+00,0.005207,0.007364,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.705036,0.771456,0.713085,0.729859,0.029596,1
7,0.046868,6.743496e-07,0.010416,0.007365,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.692497,0.719062,0.658048,0.689869,0.024978,7
8,0.026039,7.364797e-03,0.005207,0.007364,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.729301,0.741510,0.654865,0.708559,0.038293,2
9,0.031246,3.371748e-07,0.000000,0.000000,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.685415,0.669519,0.723444,0.692792,0.022624,5
10,0.020832,7.364347e-03,0.005208,0.007365,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.695517,0.712716,0.608103,0.672112,0.045803,12
11,0.031247,6.743496e-07,0.010415,0.007365,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.691018,0.680200,0.729909,0.700376,0.021345,3
12,0.010415,7.364740e-03,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.680585,0.674446,0.714654,0.689895,0.017686,6
13,0.005208,7.364797e-03,0.005209,0.007366,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.703012,0.656705,0.696180,0.685299,0.020411,9
14,0.005209,7.366033e-03,0.005209,0.007366,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.638087,0.408695,0.552911,0.533231,0.094677,18
15,0.005207,7.364010e-03,0.000616,0.000871,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.685764,0.654108,0.619679,0.653184,0.026987,13
16,0.009281,9.691962e-03,0.005157,0.007293,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.650205,0.622322,0.615654,0.629394,0.014966,15
17,0.000076,1.072216e-04,0.011861,0.008394,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.697553,0.481946,0.661938,0.613812,0.094370,16

In [15]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:33
BMI:33
Children:3
Sex Male 0 or 1:0
Smoker Yes 0 or 1:0

In [16]:
Future_Prediction = grid.predict ([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_prediction={}".format(Future_Prediction))

Future_prediction=[6551.7501]

In [17]:
import pickle
fileName="finalized_model_decision_tree_grid_01.sav"

In [18]:
pickle.dump(grid,open(fileName,'wb'))
# store or saving the regressor file /fileName 
# 'wb' means write  binary values

In [19]:
loaded_model=pickle.load(open("finalized_model_decision_tree_grid_01.sav",'rb'))
# check the function  dumped in the pickle , need to load the pickle function from filename 
# 'rb' means read binary values